import { NextResponse } from 'next/server';
const { authenticate, authorize } = require('@/lib/auth');
const { Invoice, ServiceRequest, User, Provider, Service } = require('@/lib/models');

const generateInvoiceNumber = () => { const year = new Date().getFullYear(); const rand = Math.floor(1000 + Math.random() * 9000); return `INV-${year}-${rand}`; };

export async function POST(request) {
  try {
    const authUser = authenticate(request);
    if (!authUser) return NextResponse.json({ message: 'No token, access denied' }, { status: 401 });
    if (!authorize(authUser, 'provider')) return NextResponse.json({ message: 'Access denied. Insufficient permissions.' }, { status: 403 });
    const { patientId, serviceId, originalAmount, forWhom, dependentId, notes } = await request.json();
    if (!patientId || !serviceId || !originalAmount || originalAmount <= 0) return NextResponse.json({ message: 'Patient, service, and valid amount are required' }, { status: 400 });
    const patient = await User.findByPk(patientId);
    if (!patient || patient.role !== 'patient') return NextResponse.json({ message: 'Patient not found' }, { status: 404 });
    const provider = await Provider.findOne({ where: { userId: authUser.id } });
    if (!provider) return NextResponse.json({ message: 'Provider profile not found' }, { status: 404 });
    const service = await Service.findOne({ where: { id: serviceId, providerId: provider.id } });
    if (!service) return NextResponse.json({ message: 'Service not found' }, { status: 404 });
    const serviceRequest = await ServiceRequest.create({ patientId, providerId: provider.id, serviceId, dependentId: dependentId || null, forWhom: forWhom || 'Self', notes: notes || `Bill generated by provider for ${service.name}`, status: 'completed' });
    const hasActiveMembership = patient.hasMembershipCard && patient.membershipExpiresAt && new Date(patient.membershipExpiresAt) > new Date();
    const discountPercent = hasActiveMembership ? (provider.discountPercent ?? 0) : 0;
    const commissionPercent = hasActiveMembership ? (provider.commissionPercent ?? 0) : 0;
    const discountAmount = Math.round((originalAmount * discountPercent) / 100);
    const finalAmount = originalAmount - discountAmount;
    const commissionAmount = Math.round((originalAmount * commissionPercent) / 100);
    const invoice = await Invoice.create({ invoiceNumber: generateInvoiceNumber(), requestId: serviceRequest.id, patientId, providerId: provider.id, originalAmount, discountPercent, discountAmount, finalAmount, commissionPercent, commissionAmount, paymentStatus: 'paid', paidAt: new Date() });
    return NextResponse.json({ invoice, request: serviceRequest, message: 'Bill generated successfully', breakdown: { originalAmount, discountPercent, discountAmount, finalAmount, commissionPercent, commissionAmount } }, { status: 201 });
  } catch (error) {
    return NextResponse.json({ message: error.message }, { status: 500 });
  }
}
